version: "3.9"
name: medtrax

services:
  db:
    image: postgres:15
    container_name: medtrax-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: medtrax-redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-}"]
    restart: always
    ports:
      - "6379:6379"

  web:
    image: agrim96336/medtrax-web:latest
    container_name: medtrax-web
    command: >
      sh -c "chmod -R 777 /app/static &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8000 medtrax.asgi:application"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    restart: always


  celery:
    build: .
    container_name: medtrax-celery
    command: celery -A medtrax worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db
    restart: always

  celery-beat:
    build: .
    container_name: medtrax-celery-beat
    command: celery -A medtrax beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db
    restart: always

volumes:
  postgres_data:
